# ===================================================================
# Default GitHub Scheduler Setup
# ===================================================================

name: Scheduled Jobs

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
# github scheduler not supported seconds cron feature
on:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *' # Just Run Every minute https://crontab.guru

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    # Step.1
    steps:
      - name: poc schedule cron job
        run: echo "Welcome to 극락코딩"
