# ===================================================================
# Default GitHub Scheduler Setup
# ===================================================================

name: Scheduled Jobs

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
# github scheduler not supported seconds cron feature
on:
  schedule:
    # Just Run Every 5minute https://crontab.guru
    - cron: '*/5 * * * *'

# Job Tasks
jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      # Start Job
      - name: start Job
        run: date

      # Echo
      - name: echo job
        run: echo "Welcome to 극락코딩"

      # Checkout
      - name: repository checkout
        uses: actions/checkout@v2
        with:
          repository: DongGeon0908/github-action
          token: ${{ secrets.GOOFY_GITHUB_TOKEN }}
          path: github-action

      # git add and push
      - name: Add date and push
        run: |
          date >> auto-commit.txt
          git add .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Inject Date"
          git push

      # End Job
      - name: end Job
        run: date
