# ===================================================================
# Default GitHub Scheduler Setup
# ===================================================================

name: Scheduled Jobs

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
# github scheduler not supported seconds cron feature
on:
  schedule:
    # Just Run Every 5minute https://crontab.guru
    - cron: '*/5 * * * *'

# Job Tasks
jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      # Echo
      - name: echo job
        run: echo "Welcome to 극락코딩"

      # Start Job
      - name: start Job
        run: date

      # Checkout
      - name: repository checkout
        uses: actions/checkout@v2
        with:
          repository: DongGeon0908/github-action
          token: ${{ secrets.GOOFY_GITHUB_TOKEN }}
          path: github-action

      # git add and push
      - name: Add date and push
        run: |
          date >> auto-commit.txt
          git init
          git remote add origin https://github.com/DongGeon0908/github-action
          git checkout origin main
          git add .
          git config --global user.email "wrjssmjdhappy@gmail.com"
          git config --global user.name "극락코딩"
          git commit -am "Inject Date and auto commit"
          git push --set-upstream origin main

      # End Job
      - name: end Job
        run: date
